language: cpp

dist: focal

addons:
    apt:
        sources: &default_sources
            - boost-latest
        packages: &default_packages
            - libboost1.71-all-dev

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - *default_sources
            - ubuntu-toolchain-r-test
          packages:
            - *default_packages
            - g++-8
      env:
        - MATRIX_EVAL="CC=gcc-8 && CXX=g++-8"

    - os: linux
      addons:
        apt:
          sources:
            - *default_sources
            - llvm-toolchain-trusty-5.0
          packages:
            - *default_packages
            - clang-10
      env:
        - MATRIX_EVAL="CC=clang-10 && CXX=clang++-10"

before_install:
    - eval "${MATRIX_EVAL}"

before_script:
    - mkdir build
    - cd build
    - cmake -DCMAKE_BUILD_TYPE=Release .. 

script:
    - make
